services:
  test_container_mcp_server:
    build:
      context: ./containers/mcp_server_ctn_dir
      dockerfile: Dockerfile.mcp_server
    volumes:
      - ./datas:/app/badia_files
      - ./tests_unitaires:/app/tests_unitaires
    container_name: MCP_SERVER_CONTAINER_TEST
    ports:
      - "8000:8000"
    environment:
      - MISTRAL_API_KEY=${MISTRAL_API_KEY}
      - PYTHONDONTWRITEBYTECODE=1
    healthcheck:
      test: ["CMD", "test", "-f", "/tmp/mcp_ready.txt"]
      interval: 5s
      timeout: 2s
      retries: 5
      start_period: 5s
    command: uv run pytest /app/tests_unitaires/test_mcp_logic.py