services:
  test_container_mcp_server:
    build:
      context: ./containers/mcp_server_ctn_dir
      dockerfile: Dockerfile.mcp_server
    volumes:
      - ./datas:/app/badia_files
      - ./tests_unitaires:/app/tests_unitaires
    container_name: MCP_SERVER_CONTAINER_TEST
    ports:
      - "8000:8000"
    environment:
      - MISTRAL_API_KEY=${MISTRAL_API_KEY}
    healthcheck:
      test: ["CMD", "test", "-f", "/tmp/mcp_ready.txt"]
      interval: 5s
      timeout: 2s
      retries: 5
      start_period: 5s
    command: uv run pytest /app/tests_unitaires/test_mcp_logic.py


  container_flask:
    build:
      context: ./containers/flask_ctn_dir
      dockerfile: Dockerfile.flask
    depends_on:
      container_mcp_server:
        condition: service_healthy
    volumes:
      # Pour le développement Flask (Hot Reload) : tout le dossier courant va dans /app. A supprimer quand le projet sera en prod
      - ./containers/flask_ctn_dir:/app
      # Pour les magnifiques logs json rcp du client mcp :
      - ./logs/mcp_client:/app/logs_ctn_flask
    container_name: FLASK_AND_MCP_CLIENT_CONTAINER
    ports:
      - "5000:5000"
    environment:
      - FLASK_DEBUG=1
      - MISTRAL_API_KEY=${MISTRAL_API_KEY}
