name: BADIA_CICD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  badia_pylint:
    runs-on: ubuntu-latest
    steps:
      - name: Récupération du code
        uses: actions/checkout@v4
      
      - name: Setup uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.12.12"
          
      - name: Installation dépendances
        run: uv sync
        
      - name: Run Pylint
        run: uv run pylint . --fail-under=2

  badia_docker_tests:
    runs-on: self-hosted
    steps:
      - name: Récupération du code
        uses: actions/checkout@v4

      - name: Nettoyage préventif
        run: docker compose -f docker-compose.test.yml down -v --remove-orphans || true

      - name: Build and Run Tests
        env:
            MISTRAL_API_KEY: ${{ secrets.MISTRAL_API_KEY }}
        run: |
          docker compose -f docker-compose.test.yml up --build --abort-on-container-exit --exit-code-from test_container_mcp_server

      - name: Cleanup Final
        if: always()
        run: docker compose -f docker-compose.test.yml down