name: Automatisaton raw to jpeg

on:
  schedule:
    - cron: "45 */8 * * *"
  workflow_dispatch: # garder la possibilité de la déclencher manuellement dans github

jobs:
  badia_automation_raw_to_jpeg:
    runs-on: ubuntu-latest
    steps:
      - name: Repo checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Cache pip packages
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements_raw_to_jpeg.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_raw_to_jpeg.txt
      - name: Where am I
        run: |
          pwd
          ls -la
          pip list
      - name: Run raw_to_jpeg.py
        env:
          MDP_MAIL: ${{ secrets.MDP_MAIL }}
          MAIL_SENDER_ADRESS: ${{ secrets.MAIL_SENDER_ADRESS }}
          MAIL_RECIEVER: ${{ secrets.MAIL_RECIEVER }}
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          ROOT_FOLDER_NAME: ${{ secrets.ROOT_FOLDER_NAME }}
          VIDEO_RAW_FOLDER_NAME: ${{ secrets.VIDEO_RAW_FOLDER_NAME }}
          PHOTO_RAW_FOLDER_NAME: ${{ secrets.PHOTO_RAW_FOLDER_NAME }}
          CLEANED_DATA_FOLDER_NAME: ${{ secrets.CLEANED_DATA_FOLDER_NAME }}
          TREATED_LIST_FOLDER: ${{ secrets.TREATED_LIST_FOLDER }}
          GDRIVE_SERVICE_ACCOUNT_KEY: ${{ secrets.GDRIVE_SERVICE_ACCOUNT_KEY }}
          SCOPES: ${{ secrets.SCOPES }}

        run: |
          python raw_to_jpeg.py
      - name: Persist log file
        uses: actions/upload-artifact@v4
        with:
          name: last_log_file
          path: ./logs/raw_to_jpeg.log